; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html


[env:tbeam_send_gps]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps =
  file://lib/RadioLibTrim
  mikalhart/TinyGPSPlus@^1.1.0
  plerup/EspSoftwareSerial@^8.2.0
lib_ignore =
  RadioLib
build_unflags = -Os
src_filter = +<main.cpp>



[env:tbeam_receive_gps]
platform = espressif32@6.8.1
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  file://lib/RadioLibTrim
  mikalhart/TinyGPSPlus@^1.1.0
  plerup/EspSoftwareSerial@^8.2.0
lib_ignore =
  RadioLib
build_unflags = -Os
src_filter = +<main_receive.cpp>
